In [1]:
!pip install requests pandas transformers torch

Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (2.32.4)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (4.57.3)
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (2.9.0+cu126)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests) (2025.11.12)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.20.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.34.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.36.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.1)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch) (2025.3.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.3.20 in /usr/local/lib/python3.12/dist-packages (from torch) (3.3.20)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch) (1.11.1.6)
Requirement already satisfied: triton==3.5.0 in /usr/local/lib/python3.12/dist-packages (from torch) (3.5.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (1.2.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch) (3.0.3)

In [2]:
import requests
import pandas as pd
from transformers import pipeline

API_KEY = ""
CRYPTO_PANIC_URL = "https://cryptopanic.com/api/v1/posts/"

In [4]:
params = {
    "auth_token": API_KEY,
    "public": "true",
    "kind": "news"
}

response = requests.get(CRYPTO_PANIC_URL, params=params)
data = response.json()

news_list = []

In [7]:
data['results']

[{'id': 27924326,
  'slug': 'Ethereums-2026-Setup-Draws-Attention-as-Key-On-Chain-Metrics-Align',
  'title': 'Ethereum’s 2026 Setup Draws Attention as Key On-Chain Metrics Align',
  'description': 'Ethereum is back in focus after two influential analysts highlighted patterns that mirror previous cycle expansions. A combination of long-term technical structure and whale-level cost basis signals has revived speculation that ETH could be preparing for a major breakout heading into 2026.',
  'published_at': '2025-12-13T18:40:16Z',
  'created_at': '2025-12-13T18:40:16+00:00',
  'kind': 'news'},
 {'id': 27924327,
  'slug': 'Ripples-Brad-Garlinghouse-Shares-Key-Institutional-Signal-Makes-Bold-XRP-Prediction-For-2026',
  'title': 'Ripple’s Brad Garlinghouse Shares Key Institutional Signal, Makes Bold XRP Prediction For 2026\u202c',
  'description': 'Ripple CEO Brad Garlinghouse has outlined what he considers one of the clearest signs that institutional capital is finally entering the crypto market, despite recent volatility. Speaking at Binance Blockchain Week alongside Solana Foundation President Lily Liu and Binance CEO Richard Teng, Garlinghouse said XRP ETFs have already raised over $700 million in just a [&#8230;]',
  'published_at': '2025-12-13T18:37:27Z',
  'created_at': '2025-12-13T18:37:27+00:00',
  'kind': 'news'},
 {'id': 27926912,
  'slug': 'Exor-Rejects-Tethers-Acquisition-Proposal-for-Juventus',
  'title': "Exor Rejects Tether's Acquisition Proposal for Juventus",
  'description': "Exor rebuffs Tether's offer to acquire its Juventus stake, confirming no intent to sell.",
  'published_at': '2025-12-13T18:34:39Z',
  'created_at': '2025-12-13T18:34:39+00:00',
  'kind': 'news'},
 {'id': 27924320,
  'slug': 'Coinbase-to-Add-Prediction-Market-Ahead-of-Major-Dec-17-Event',
  'title': 'Coinbase to Add Prediction Market Ahead of Major Dec. 17 Event',
  'description': 'Coinbase plans to increase its wide range of crypto services with the addition of a prediction market in collaboration with the popular crypto prediction platform Kalshi.',
  'published_at': '2025-12-13T18:33:00Z',
  'created_at': '2025-12-13T18:33:00+00:00',
  'kind': 'news'},
 {'id': 27924295,
  'slug': 'Best-Crypto-to-Buy-Now-Holiday-Drops-Go-Live-Digitap-TAP-Brings-A-Deflationary-Banking-Story-Into-Year-End',
  'title': 'Best Crypto to Buy Now? Holiday Drops Go Live – Digitap ($TAP) Brings A Deflationary Banking Story Into Year-End',
  'description': 'Crypto investors have begun searching for top altcoins to buy as the year draws to a close. While the crypto market offers many opportunities, the sheer number of altcoins makes finding the best crypto to buy now a daunting task for many investors.',
  'published_at': '2025-12-13T18:30:57Z',
  'created_at': '2025-12-13T18:30:57+00:00',
  'kind': 'news'},
 {'id': 27924284,
  'slug': 'Almost-One-Third-of-Bitcoin-BTC-Is-Held-by-Big-Players-Glassnode-Finds',
  'title': 'Almost One-Third of Bitcoin (BTC) Is Held by Big Players: Glassnode Finds',
  'description': "Bitcoin's ownership profile is changing. Corporate treasuries and governments are now holding sizable portions of the circulating supply.",
  'published_at': '2025-12-13T18:18:01Z',
  'created_at': '2025-12-13T18:18:01+00:00',
  'kind': 'news'},
 {'id': 27925020,
  'slug': 'iAero-Launches-Token-Sweeper-LIQ-Rewards',
  'title': 'iAero Launches Token Sweeper & LIQ Rewards',
  'description': 'iAero unveils Token Sweeper and a six-month campaign rewarding stakers with 5% of LIQ token supply',
  'published_at': '2025-12-13T18:13:00Z',
  'created_at': '2025-12-13T18:13:00+00:00',
  'kind': 'news'},
 {'id': 27924369,
  'slug': 'Rare-Market-Exhaustion-Indicator-Suggests-Bitcoin-May-Be-Near-a-Turning-Point',
  'title': 'Rare Market Exhaustion Indicator Suggests Bitcoin May Be Near a Turning Point',
  'description': 'Bitcoin may be approaching a pivotal moment, as one of the market’s most extreme stress indicators has just printed its highest reading ever - a signal that has historically appeared near major turning points.',
  'published_at': '2025-12-13T18:00:48Z',
  'created_at': '2025-12-13T18:00:48+00:00',
  'kind': 'news'},
 {'id': 27931779,
  'slug': 'Solana-ETFs-Attract-Significant-Inflows-Amid-Market-Challenges',
  'title': 'Solana ETFs Attract Significant Inflows Amid Market Challenges',
  'description': "According to Cointelegraph, Solana (SOL) exchange-traded funds (ETFs) have experienced a consistent inflow streak over seven days, despite the cryptocurrency's declining price and a broader downturn in the crypto market. On Tuesday, the inflows peaked with approximately $16. 6 million directed into SOL ETFs, as reported by investment management firm Farside Investors. This brings the total net inflow into SOL ETFs to $674 million at the time of writing, based on Farside's data",
  'published_at': '2025-12-13T17:53:46Z',
  'created_at': '2025-12-13T17:53:46+00:00',
  'kind': 'news'},
 {'id': 27923560,
  'slug': 'Bank-CEO-Issues-Fraudulent-Loans-to-Friends-and-Neighbors-Manipulating-Records-To-Hide-Scheme-From-Banks-Board-and-US-Government-DOJ',
  'title': 'Bank CEO Issues Fraudulent Loans to Friends and Neighbors, Manipulating Records To Hide Scheme From Bank’s Board and US Government: DOJ',
  'description': 'A US bank executive is facing federal fraud charges after allegedly steering his institution into a years-long scheme that enriched friends, neighbors, and favored borrowers while concealing the truth from regulators and his own board.',
  'published_at': '2025-12-13T17:48:43Z',
  'created_at': '2025-12-13T17:48:43+00:00',
  'kind': 'news'},
 {'id': 27923554,
  'slug': 'Solana-ETFs-record-7-day-inflow-streak-despite-price-slump',
  'title': 'Solana ETFs record 7-day inflow streak despite price slump',
  'description': 'The first SOL ETF was launched in July, followed by Bitwise’s SOL ETF in October, which recorded $57 million in first-day trading volume.',
  'published_at': '2025-12-13T17:44:25Z',
  'created_at': '2025-12-13T17:44:25+00:00',
  'kind': 'news'},
 {'id': 27923543,
  'slug': 'As-US-Pressure-Against-Venezuela-Builds-Polymarket-Bettors-Handicap-Maduros-Exit-Timing',
  'title': 'As US Pressure Against Venezuela Builds, Polymarket Bettors Handicap Maduro’s Exit Timing',
  'description': 'Over the past year, tensions between the U. S. and Venezuela have heated up heading into late 2025 under President Trump, marked by U. S. maritime strikes, tanker seizures, and sanctions aimed squarely at Nicolás Maduro’s regime. Polymarket bettors say the odds of Maduro being pushed from power are ticking higher, with a 21% chance it happens [&#8230;]',
  'published_at': '2025-12-13T17:43:06Z',
  'created_at': '2025-12-13T17:43:06+00:00',
  'kind': 'news'},
 {'id': 27923541,
  'slug': 'Nvidia-wants-to-boost-H200-chip-production-to-appease-China',
  'title': 'Nvidia wants to boost H200 chip production to appease China',
  'description': 'Nvidia is weighing a plan to expand output for its H200 chips after Chinese buyers pushed demand far beyond what the company can produce right now. According to Reuters, the company told clients in China that it is studying ways to add capacity because orders have gone past its current limits. The push began after [&#8230;]',
  'published_at': '2025-12-13T17:38:14Z',
  'created_at': '2025-12-13T17:38:14+00:00',
  'kind': 'news'},
 {'id': 27923535,
  'slug': 'Top-Brazilian-Bank-Recommends-Bitcoin-Allocation-for-Investor-Portfolios',
  'title': 'Top Brazilian Bank Recommends Bitcoin Allocation for Investor Portfolios',
  'description': 'That perception is now quietly changing &#8211; and Brazil&#8217;s largest private banking group is part of the shift.',
  'published_at': '2025-12-13T17:34:08Z',
  'created_at': '2025-12-13T17:34:08+00:00',
  'kind': 'news'},
 {'id': 27923540,
  'slug': 'Musks-SpaceX-IPO-plans-confirmed-for-2026-at-800B-valuation',
  'title': 'Musk’s SpaceX IPO plans confirmed for 2026 at $800B valuation',
  'description': 'SpaceX is currently expected to launch an IPO in 2026, valuing it at $800 billion. With the current investor interest in the Musk-led venture, SpaceX could raise more than $25 billion with its potential public offering expected to launch next year. According to a letter from SpaceX CFO Bret Johnsen reviewed by Reuters, the company [&#8230;]',
  'published_at': '2025-12-13T17:30:24Z',
  'created_at': '2025-12-13T17:30:24+00:00',
  'kind': 'news'},
 {'id': 27923544,
  'slug': 'JPMorgan-Boss-Favors-Kevin-Warsh-As-Next-Fed-Chair',
  'title': 'JPMorgan Boss Favors Kevin Warsh As Next Fed Chair',
  'description': 'JPMorgan Chief Executive Officer Jamie Dimon signaled support for former Federal Reserve \u200bGovernor Kevin Warsh as the next \u200cFed Chair.',
  'published_at': '2025-12-13T17:30:00Z',
  'created_at': '2025-12-13T17:30:00+00:00',
  'kind': 'news'},
 {'id': 27923162,
  'slug': 'AI-predicts-XRP-price-if-ETF-inflows-will-hit-10-billion',
  'title': 'AI predicts XRP price if ETF inflows will hit $10 billion',
  'description': 'XRP exchange-traded funds (ETF) are posting one of the fastest adoption rates seen in the cryptocurrency ETF market, with cumulative inflows nearing $1 billion within just three to four weeks of launch. The pace exceeds early inflow trends recorded by Bitcoin (BTC) and Ethereum (ETH) ETFs, signaling strong institutional appetite for XRP-linked investment products. Flow data shows inflows have remained consistently positive, with no notable net outflows reported so far. Meanwhile, XRP has continued to trade near the $2 level, a key psychological zone',
  'published_at': '2025-12-13T17:26:52Z',
  'created_at': '2025-12-13T17:26:52+00:00',
  'kind': 'news'},
 {'id': 27924343,
  'slug': 'Michael-Saylors-Strategy-Hangs-on-to-Spot-in-Nasdaq-100-Index',
  'title': "Michael Saylor's Strategy Hangs on to Spot in Nasdaq 100 Index",
  'description': "Michael Saylor's innovative investment strategy has successfully maintained its position within the prestigious Nasdaq 100 Index, demonstrating resilience and adaptability in a rapidly changing market environment.",
  'published_at': '2025-12-13T17:23:19Z',
  'created_at': '2025-12-13T17:23:19+00:00',
  'kind': 'news'},
 {'id': 27923472,
  'slug': 'LATEST-Netflix-has-revealed-that-Jennifer-Garner-will-star-in-a-new-crypto-themed-comedy-called-One-Attempt-Remaining-about-a-divorced-couple-trying-to-track-down-the-password-for-an-old-crypto-account-now-worth-millions',
  'title': 'LATEST:  Netflix has revealed that Jennifer Garner will star in a new crypto-themed comedy called "One Attempt Remaining" about a divorced couple trying to track down the password for an old crypto account now worth millions.',
  'description': None,
  'published_at': '2025-12-13T17:23:06Z',
  'created_at': '2025-12-13T17:23:06+00:00',
  'kind': 'news'},
 {'id': 27922867,
  'slug': 'Brazils-Biggest-Bank-Recommends-Bitcoin-Allocation-of-Up-to-3',
  'title': 'Brazil’s Biggest Bank Recommends Bitcoin Allocation of Up to 3%',
  'description': 'Itaú Unibanco, the largest private bank in Brazil and all of Latin America, has taken another major step toward institutional crypto adoption by formally recommending that clients allocate a portion of their portfolios to Bitcoin. The guidance comes from Itaú Asset, the bank’s asset management arm overseeing roughly $185 billion in assets.',
  'published_at': '2025-12-13T17:23:03Z',
  'created_at': '2025-12-13T17:23:03+00:00',
  'kind': 'news'}]

In [15]:
for item in data["results"]:
    news_list.append({
        "title": item["title"],
        "description":item["description"],
        "published_at": item["published_at"]
    })

df = pd.DataFrame(news_list)

# Combine title + summary
df["text"] = df["title"] + ". " + df["description"].str.strip()
df = df[df["text"] != ""]

In [16]:
print(f"Fetched {len(df)} news articles")

Fetched 60 news articles

In [17]:
df

,title,description,published_at,text
0,Ethereum’s 2026 Setup Draws Attention as Key O...,Ethereum is back in focus after two influentia...,2025-12-13T18:40:16Z,Ethereum’s 2026 Setup Draws Attention as Key O...
1,Ripple’s Brad Garlinghouse Shares Key Institut...,Ripple CEO Brad Garlinghouse has outlined what...,2025-12-13T18:37:27Z,Ripple’s Brad Garlinghouse Shares Key Institut...
2,Exor Rejects Tether's Acquisition Proposal for...,Exor rebuffs Tether's offer to acquire its Juv...,2025-12-13T18:34:39Z,Exor Rejects Tether's Acquisition Proposal for...
3,Coinbase to Add Prediction Market Ahead of Maj...,Coinbase plans to increase its wide range of c...,2025-12-13T18:33:00Z,Coinbase to Add Prediction Market Ahead of Maj...
4,Best Crypto to Buy Now? Holiday Drops Go Live ...,Crypto investors have begun searching for top ...,2025-12-13T18:30:57Z,Best Crypto to Buy Now? Holiday Drops Go Live ...
5,Almost One-Third of Bitcoin (BTC) Is Held by B...,Bitcoin's ownership profile is changing. Corpo...,2025-12-13T18:18:01Z,Almost One-Third of Bitcoin (BTC) Is Held by B...
6,iAero Launches Token Sweeper & LIQ Rewards,iAero unveils Token Sweeper and a six-month ca...,2025-12-13T18:13:00Z,iAero Launches Token Sweeper & LIQ Rewards. iA...
7,Rare Market Exhaustion Indicator Suggests Bitc...,"Bitcoin may be approaching a pivotal moment, a...",2025-12-13T18:00:48Z,Rare Market Exhaustion Indicator Suggests Bitc...
8,Solana ETFs Attract Significant Inflows Amid M...,"According to Cointelegraph, Solana (SOL) excha...",2025-12-13T17:53:46Z,Solana ETFs Attract Significant Inflows Amid M...
9,Bank CEO Issues Fraudulent Loans to Friends an...,A US bank executive is facing federal fraud ch...,2025-12-13T17:48:43Z,Bank CEO Issues Fraudulent Loans to Friends an...
10,Solana ETFs record 7-day inflow streak despite...,"The first SOL ETF was launched in July, follow...",2025-12-13T17:44:25Z,Solana ETFs record 7-day inflow streak despite...
11,"As US Pressure Against Venezuela Builds, Polym...","Over the past year, tensions between the U. S....",2025-12-13T17:43:06Z,"As US Pressure Against Venezuela Builds, Polym..."
12,Nvidia wants to boost H200 chip production to ...,Nvidia is weighing a plan to expand output for...,2025-12-13T17:38:14Z,Nvidia wants to boost H200 chip production to ...
13,Top Brazilian Bank Recommends Bitcoin Allocati...,That perception is now quietly changing &#8211...,2025-12-13T17:34:08Z,Top Brazilian Bank Recommends Bitcoin Allocati...
14,Musk’s SpaceX IPO plans confirmed for 2026 at ...,SpaceX is currently expected to launch an IPO ...,2025-12-13T17:30:24Z,Musk’s SpaceX IPO plans confirmed for 2026 at ...
15,JPMorgan Boss Favors Kevin Warsh As Next Fed C...,JPMorgan Chief Executive Officer Jamie Dimon s...,2025-12-13T17:30:00Z,JPMorgan Boss Favors Kevin Warsh As Next Fed C...
16,AI predicts XRP price if ETF inflows will hit ...,XRP exchange-traded funds (ETF) are posting on...,2025-12-13T17:26:52Z,AI predicts XRP price if ETF inflows will hit ...
17,Michael Saylor's Strategy Hangs on to Spot in ...,Michael Saylor's innovative investment strateg...,2025-12-13T17:23:19Z,Michael Saylor's Strategy Hangs on to Spot in ...
18,LATEST: Netflix has revealed that Jennifer Ga...,None,2025-12-13T17:23:06Z,NaN
19,Brazil’s Biggest Bank Recommends Bitcoin Alloc...,"Itaú Unibanco, the largest private bank in Bra...",2025-12-13T17:23:03Z,Brazil’s Biggest Bank Recommends Bitcoin Alloc...
20,Ethereum’s 2026 Setup Draws Attention as Key O...,Ethereum is back in focus after two influentia...,2025-12-13T18:40:16Z,Ethereum’s 2026 Setup Draws Attention as Key O...
21,Ripple’s Brad Garlinghouse Shares Key Institut...,Ripple CEO Brad Garlinghouse has outlined what...,2025-12-13T18:37:27Z,Ripple’s Brad Garlinghouse Shares Key Institut...
22,Exor Rejects Tether's Acquisition Proposal for...,Exor rebuffs Tether's offer to acquire its Juv...,2025-12-13T18:34:39Z,Exor Rejects Tether's Acquisition Proposal for...
23,Coinbase to Add Prediction Market Ahead of Maj...,Coinbase plans to increase its wide range of c...,2025-12-13T18:33:00Z,Coinbase to Add Prediction Market Ahead of Maj...
24,Best Crypto to Buy Now? Holiday Drops Go Live ...,Crypto investors have begun searching for top ...,2025-12-13T18:30:57Z,Best Crypto to Buy Now? Holiday Drops Go Live ...
25,Almost One-Third of Bitcoin (BTC) Is Held by B...,Bitcoin's ownership profile is changing. Corpo...,2025-12-13T18:18:01Z,Almost One-Third of Bitcoin (BTC) Is Held by B...
26,iAero Launches Token Sweeper & LIQ Rewards,iAero unveils Token Sweeper and a six-month ca...,2025-12-13T18:13:00Z,iAero Launches Token Sweeper & LIQ Rewards. iA...
27,Rare Market Exhaustion Indicator Suggests Bitc...,"Bitcoin may be approaching a pivotal moment, a...",2025-12-13T18:00:48Z,Rare Market Exhaustion Indicator Suggests Bitc...
28,Solana ETFs Attract Significant Inflows Amid M...,"According to Cointelegraph, Solana (SOL) excha...",2025-12-13T17:53:46Z,Solana ETFs Attract Significant Inflows Amid M...
29,Bank CEO Issues Fraudulent Loans to Friends an...,A US bank executive is facing federal fraud ch...,2025-12-13T17:48:43Z,Bank CEO Issues Fraudulent Loans to Friends an...
30,Solana ETFs record 7-day inflow streak despite...,"The first SOL ETF was launched in July, follow...",2025-12-13T17:44:25Z,Solana ETFs record 7-day inflow streak despite...
31,"As US Pressure Against Venezuela Builds, Polym...","Over the past year, tensions between the U. S....",2025-12-13T17:43:06Z,"As US Pressure Against Venezuela Builds, Polym..."
32,Nvidia wants to boost H200 chip production to ...,Nvidia is weighing a plan to expand output for...,2025-12-13T17:38:14Z,Nvidia wants to boost H200 chip production to ...
33,Top Brazilian Bank Recommends Bitcoin Allocati...,That perception is now quietly changing &#8211...,2025-12-13T17:34:08Z,Top Brazilian Bank Recommends Bitcoin Allocati...
34,Musk’s SpaceX IPO plans confirmed for 2026 at ...,SpaceX is currently expected to launch an IPO ...,2025-12-13T17:30:24Z,Musk’s SpaceX IPO plans confirmed for 2026 at ...
35,JPMorgan Boss Favors Kevin Warsh As Next Fed C...,JPMorgan Chief Executive Officer Jamie Dimon s...,2025-12-13T17:30:00Z,JPMorgan Boss Favors Kevin Warsh As Next Fed C...
36,AI predicts XRP price if ETF inflows will hit ...,XRP exchange-traded funds (ETF) are posting on...,2025-12-13T17:26:52Z,AI predicts XRP price if ETF inflows will hit ...
37,Michael Saylor's Strategy Hangs on to Spot in ...,Michael Saylor's innovative investment strateg...,2025-12-13T17:23:19Z,Michael Saylor's Strategy Hangs on to Spot in ...
38,LATEST: Netflix has revealed that Jennifer Ga...,None,2025-12-13T17:23:06Z,NaN
39,Brazil’s Biggest Bank Recommends Bitcoin Alloc...,"Itaú Unibanco, the largest private bank in Bra...",2025-12-13T17:23:03Z,Brazil’s Biggest Bank Recommends Bitcoin Alloc...
40,Ethereum’s 2026 Setup Draws Attention as Key O...,Ethereum is back in focus after two influentia...,2025-12-13T18:40:16Z,Ethereum’s 2026 Setup Draws Attention as Key O...
41,Ripple’s Brad Garlinghouse Shares Key Institut...,Ripple CEO Brad Garlinghouse has outlined what...,2025-12-13T18:37:27Z,Ripple’s Brad Garlinghouse Shares Key Institut...
42,Exor Rejects Tether's Acquisition Proposal for...,Exor rebuffs Tether's offer to acquire its Juv...,2025-12-13T18:34:39Z,Exor Rejects Tether's Acquisition Proposal for...
43,Coinbase to Add Prediction Market Ahead of Maj...,Coinbase plans to increase its wide range of c...,2025-12-13T18:33:00Z,Coinbase to Add Prediction Market Ahead of Maj...
44,Best Crypto to Buy Now? Holiday Drops Go Live ...,Crypto investors have begun searching for top ...,2025-12-13T18:30:57Z,Best Crypto to Buy Now? Holiday Drops Go Live ...
45,Almost One-Third of Bitcoin (BTC) Is Held by B...,Bitcoin's ownership profile is changing. Corpo...,2025-12-13T18:18:01Z,Almost One-Third of Bitcoin (BTC) Is Held by B...
46,iAero Launches Token Sweeper & LIQ Rewards,iAero unveils Token Sweeper and a six-month ca...,2025-12-13T18:13:00Z,iAero Launches Token Sweeper & LIQ Rewards. iA...
47,Rare Market Exhaustion Indicator Suggests Bitc...,"Bitcoin may be approaching a pivotal moment, a...",2025-12-13T18:00:48Z,Rare Market Exhaustion Indicator Suggests Bitc...
48,Solana ETFs Attract Significant Inflows Amid M...,"According to Cointelegraph, Solana (SOL) excha...",2025-12-13T17:53:46Z,Solana ETFs Attract Significant Inflows Amid M...
49,Bank CEO Issues Fraudulent Loans to Friends an...,A US bank executive is facing federal fraud ch...,2025-12-13T17:48:43Z,Bank CEO Issues Fraudulent Loans to Friends an...
50,Solana ETFs record 7-day inflow streak despite...,"The first SOL ETF was launched in July, follow...",2025-12-13T17:44:25Z,Solana ETFs record 7-day inflow streak despite...
51,"As US Pressure Against Venezuela Builds, Polym...","Over the past year, tensions between the U. S....",2025-12-13T17:43:06Z,"As US Pressure Against Venezuela Builds, Polym..."
52,Nvidia wants to boost H200 chip production to ...,Nvidia is weighing a plan to expand output for...,2025-12-13T17:38:14Z,Nvidia wants to boost H200 chip production to ...
53,Top Brazilian Bank Recommends Bitcoin Allocati...,That perception is now quietly changing &#8211...,2025-12-13T17:34:08Z,Top Brazilian Bank Recommends Bitcoin Allocati...
54,Musk’s SpaceX IPO plans confirmed for 2026 at ...,SpaceX is currently expected to launch an IPO ...,2025-12-13T17:30:24Z,Musk’s SpaceX IPO plans confirmed for 2026 at ...
55,JPMorgan Boss Favors Kevin Warsh As Next Fed C...,JPMorgan Chief Executive Officer Jamie Dimon s...,2025-12-13T17:30:00Z,JPMorgan Boss Favors Kevin Warsh As Next Fed C...
56,AI predicts XRP price if ETF inflows will hit ...,XRP exchange-traded funds (ETF) are posting on...,2025-12-13T17:26:52Z,AI predicts XRP price if ETF inflows will hit ...
57,Michael Saylor's Strategy Hangs on to Spot in ...,Michael Saylor's innovative investment strateg...,2025-12-13T17:23:19Z,Michael Saylor's Strategy Hangs on to Spot in ...
58,LATEST: Netflix has revealed that Jennifer Ga...,None,2025-12-13T17:23:06Z,NaN
59,Brazil’s Biggest Bank Recommends Bitcoin Alloc...,"Itaú Unibanco, the largest private bank in Bra...",2025-12-13T17:23:03Z,Brazil’s Biggest Bank Recommends Bitcoin Alloc...

In [13]:
sentiment_pipeline = pipeline(
    "sentiment-analysis",
    model="ProsusAI/finbert",
    tokenizer="ProsusAI/finbert"
)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/758 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/438M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/252 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

Device set to use cuda:0

In [18]:
texts = df["text"].astype(str).tolist()
results = sentiment_pipeline(
    texts,
    truncation=True
)

df["sentiment"] = [r["label"].lower() for r in results]
df["confidence"] = [r["score"] for r in results]

In [19]:
df.to_csv("crypto_news_finbert_sentiment.csv", index=False)
print("Saved results to crypto_news_finbert_sentiment.csv")

Saved results to crypto_news_finbert_sentiment.csv

In [22]:
df.head()

,title,description,published_at,text,sentiment,confidence
0,Ethereum’s 2026 Setup Draws Attention as Key O...,Ethereum is back in focus after two influentia...,2025-12-13T18:40:16Z,Ethereum’s 2026 Setup Draws Attention as Key O...,positive,0.940718
1,Ripple’s Brad Garlinghouse Shares Key Institut...,Ripple CEO Brad Garlinghouse has outlined what...,2025-12-13T18:37:27Z,Ripple’s Brad Garlinghouse Shares Key Institut...,positive,0.844455
2,Exor Rejects Tether's Acquisition Proposal for...,Exor rebuffs Tether's offer to acquire its Juv...,2025-12-13T18:34:39Z,Exor Rejects Tether's Acquisition Proposal for...,negative,0.867390
3,Coinbase to Add Prediction Market Ahead of Maj...,Coinbase plans to increase its wide range of c...,2025-12-13T18:33:00Z,Coinbase to Add Prediction Market Ahead of Maj...,positive,0.861603
4,Best Crypto to Buy Now? Holiday Drops Go Live ...,Crypto investors have begun searching for top ...,2025-12-13T18:30:57Z,Best Crypto to Buy Now? Holiday Drops Go Live ...,neutral,0.598799

In [26]:
print(df[["title","description","published_at","text","sentiment","confidence"]].head())

                                               title  \
0  Ethereum’s 2026 Setup Draws Attention as Key O...
1  Ripple’s Brad Garlinghouse Shares Key Institut...
2  Exor Rejects Tether's Acquisition Proposal for...
3  Coinbase to Add Prediction Market Ahead of Maj...
4  Best Crypto to Buy Now? Holiday Drops Go Live ...

                                         description          published_at  \
0  Ethereum is back in focus after two influentia...  2025-12-13T18:40:16Z
1  Ripple CEO Brad Garlinghouse has outlined what...  2025-12-13T18:37:27Z
2  Exor rebuffs Tether's offer to acquire its Juv...  2025-12-13T18:34:39Z
3  Coinbase plans to increase its wide range of c...  2025-12-13T18:33:00Z
4  Crypto investors have begun searching for top ...  2025-12-13T18:30:57Z

                                                text sentiment  confidence
0  Ethereum’s 2026 Setup Draws Attention as Key O...  positive    0.940718
1  Ripple’s Brad Garlinghouse Shares Key Institut...  positive    0.844455
2  Exor Rejects Tether's Acquisition Proposal for...  negative    0.867390
3  Coinbase to Add Prediction Market Ahead of Maj...  positive    0.861603
4  Best Crypto to Buy Now? Holiday Drops Go Live ...   neutral    0.598799